use_frameworks!

target 'RDMWaveformView_Example' do
  pod 'SparseRanges', :git => 'git@reedom.github.com:reedom/SparseRanges.git'
  pod 'RDMWaveformView', :path => '../'

  target 'RDMWaveformView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0.0'
    pod 'Nimble', '~> 8.0.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
